spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=mk115_spring
    username: postgres
    password: 12345678
  jpa:
    show-sql: true
    hibernate.ddl-auto: update